### ISSUE TITLE
EmoLex

### ISSUE THREAD

**Issue by LZXYF** [tsosea2/eMLM#1]
Can you provide the data content of EmoLex? 
I couldn't find the lexicon in "CROWDSOURCING A WORD-EMOTION ASSOCIATION LEXICON".

**Comment by flowerymarch** [comment]
Could you please provide the hole datadets for training? I use the huggingface's load_datasets, but the data is incomplete, I only can have a 17G wikipedia datasets. And what about the checkpoint? Thank you!

**Comment by tsosea2** [comment]
You can find emolex here: https://saifmohammad.com/WebPages/NRC-Emotion-Lexicon.htm. The wikipedia dataset used is the one from HuggingFace, it contains ~2,500M words (as reported in the original BERT paper). The pre-trained model is now available.
